-- AlterEnum
ALTER TYPE "LeaseActivityAction" ADD VALUE IF NOT EXISTS 'PARKING_ALLOCATION_ENDED';
ALTER TYPE "LeaseActivityAction" ADD VALUE IF NOT EXISTS 'VEHICLE_ADDED';
ALTER TYPE "LeaseActivityAction" ADD VALUE IF NOT EXISTS 'VEHICLE_UPDATED';
ALTER TYPE "LeaseActivityAction" ADD VALUE IF NOT EXISTS 'VEHICLE_DELETED';
