ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNER_APPROVAL_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNER_APPROVAL_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNER_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNER_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNER_REQUEST_OVERRIDDEN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNER_ACCESS_GRANTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNER_ACCESS_DISABLED';
