-- Backfill missing RolePermission rows for system role templates.
--
-- RBAC v2 introduced org-scoped and building-scoped system templates, but some
-- environments ended up with Role rows and UserAccessAssignment rows without the
-- corresponding RolePermission rows when the follow-up seed/backfill step did
-- not run. This migration repairs the source-of-truth permission bindings for
-- all built-in system templates so building/org access does not depend on seed
-- execution order.

WITH desired_role_permissions("roleKey", "permissionKey", "orgScoped") AS (
  VALUES
    ('org_admin', 'users.read', true),
    ('org_admin', 'users.write', true),
    ('org_admin', 'roles.read', true),
    ('org_admin', 'roles.write', true),
    ('org_admin', 'dashboard.read', true),
    ('org_admin', 'buildings.read', true),
    ('org_admin', 'buildings.write', true),
    ('org_admin', 'units.read', true),
    ('org_admin', 'units.write', true),
    ('org_admin', 'unitTypes.read', true),
    ('org_admin', 'unitTypes.write', true),
    ('org_admin', 'building.assignments.read', true),
    ('org_admin', 'building.assignments.write', true),
    ('org_admin', 'occupancy.read', true),
    ('org_admin', 'occupancy.write', true),
    ('org_admin', 'leases.read', true),
    ('org_admin', 'leases.write', true),
    ('org_admin', 'leases.documents.read', true),
    ('org_admin', 'leases.documents.write', true),
    ('org_admin', 'leases.access_items.read', true),
    ('org_admin', 'leases.access_items.write', true),
    ('org_admin', 'leases.occupants.read', true),
    ('org_admin', 'leases.occupants.write', true),
    ('org_admin', 'leases.move_in', true),
    ('org_admin', 'leases.move_out', true),
    ('org_admin', 'contracts.read', true),
    ('org_admin', 'contracts.write', true),
    ('org_admin', 'contracts.documents.read', true),
    ('org_admin', 'contracts.documents.write', true),
    ('org_admin', 'contracts.occupants.read', true),
    ('org_admin', 'contracts.occupants.write', true),
    ('org_admin', 'contracts.move_in_request.create', true),
    ('org_admin', 'contracts.move_out_request.create', true),
    ('org_admin', 'contracts.move_requests.review', true),
    ('org_admin', 'contracts.move_in.execute', true),
    ('org_admin', 'contracts.move_out.execute', true),
    ('org_admin', 'residents.read', true),
    ('org_admin', 'residents.write', true),
    ('org_admin', 'residents.profile.read', true),
    ('org_admin', 'residents.profile.write', true),
    ('org_admin', 'owners.read', true),
    ('org_admin', 'owners.write', true),
    ('org_admin', 'owner_registry.resolve', true),
    ('org_admin', 'owner_access_grants.read', true),
    ('org_admin', 'owner_access_grants.write', true),
    ('org_admin', 'service_providers.read', true),
    ('org_admin', 'service_providers.write', true),
    ('org_admin', 'requests.read', true),
    ('org_admin', 'requests.write', true),
    ('org_admin', 'requests.assign', true),
    ('org_admin', 'requests.update_status', true),
    ('org_admin', 'requests.comment', true),
    ('org_admin', 'requests.owner_approval_override', true),
    ('org_admin', 'org.profile.write', true),
    ('org_admin', 'parkingSlots.create', true),
    ('org_admin', 'parkingSlots.read', true),
    ('org_admin', 'parkingSlots.update', true),
    ('org_admin', 'parkingAllocations.create', true),
    ('org_admin', 'parkingAllocations.read', true),
    ('org_admin', 'parkingAllocations.end', true),
    ('org_admin', 'vehicles.create', true),
    ('org_admin', 'vehicles.read', true),
    ('org_admin', 'vehicles.update', true),
    ('org_admin', 'vehicles.delete', true),
    ('org_admin', 'visitors.create', true),
    ('org_admin', 'visitors.read', true),
    ('org_admin', 'visitors.update', true),
    ('org_admin', 'broadcasts.read', true),
    ('org_admin', 'broadcasts.write', true),
    ('org_admin', 'notifications.read', true),
    ('org_admin', 'notifications.write', true),
    ('org_admin', 'messaging.read', true),
    ('org_admin', 'messaging.write', true),

    ('viewer', 'users.read', true),
    ('viewer', 'roles.read', true),
    ('viewer', 'dashboard.read', true),
    ('viewer', 'buildings.read', true),
    ('viewer', 'units.read', true),
    ('viewer', 'unitTypes.read', true),
    ('viewer', 'owners.read', true),
    ('viewer', 'owner_access_grants.read', true),
    ('viewer', 'service_providers.read', true),
    ('viewer', 'residents.read', true),
    ('viewer', 'residents.profile.read', true),
    ('viewer', 'occupancy.read', true),
    ('viewer', 'leases.read', true),
    ('viewer', 'leases.documents.read', true),
    ('viewer', 'leases.access_items.read', true),
    ('viewer', 'leases.occupants.read', true),
    ('viewer', 'contracts.read', true),
    ('viewer', 'contracts.documents.read', true),
    ('viewer', 'contracts.occupants.read', true),
    ('viewer', 'requests.read', true),
    ('viewer', 'parkingSlots.read', true),
    ('viewer', 'parkingAllocations.read', true),
    ('viewer', 'vehicles.read', true),
    ('viewer', 'visitors.read', true),
    ('viewer', 'broadcasts.read', true),
    ('viewer', 'notifications.read', true),
    ('viewer', 'notifications.write', true),
    ('viewer', 'messaging.read', true),

    ('building_admin', 'buildings.read', true),
    ('building_admin', 'buildings.write', true),
    ('building_admin', 'units.read', true),
    ('building_admin', 'units.write', true),
    ('building_admin', 'building.assignments.read', true),
    ('building_admin', 'building.assignments.write', true),
    ('building_admin', 'occupancy.read', true),
    ('building_admin', 'occupancy.write', true),
    ('building_admin', 'leases.read', true),
    ('building_admin', 'leases.write', true),
    ('building_admin', 'leases.documents.read', true),
    ('building_admin', 'leases.documents.write', true),
    ('building_admin', 'leases.access_items.read', true),
    ('building_admin', 'leases.access_items.write', true),
    ('building_admin', 'leases.occupants.read', true),
    ('building_admin', 'leases.occupants.write', true),
    ('building_admin', 'leases.move_in', true),
    ('building_admin', 'leases.move_out', true),
    ('building_admin', 'contracts.read', true),
    ('building_admin', 'contracts.write', true),
    ('building_admin', 'contracts.documents.read', true),
    ('building_admin', 'contracts.documents.write', true),
    ('building_admin', 'contracts.occupants.read', true),
    ('building_admin', 'contracts.occupants.write', true),
    ('building_admin', 'contracts.move_requests.review', true),
    ('building_admin', 'contracts.move_in.execute', true),
    ('building_admin', 'contracts.move_out.execute', true),
    ('building_admin', 'residents.read', true),
    ('building_admin', 'residents.write', true),
    ('building_admin', 'residents.profile.read', true),
    ('building_admin', 'residents.profile.write', true),
    ('building_admin', 'requests.read', true),
    ('building_admin', 'requests.write', true),
    ('building_admin', 'requests.assign', true),
    ('building_admin', 'requests.update_status', true),
    ('building_admin', 'requests.comment', true),
    ('building_admin', 'parkingSlots.create', true),
    ('building_admin', 'parkingSlots.read', true),
    ('building_admin', 'parkingSlots.update', true),
    ('building_admin', 'parkingAllocations.create', true),
    ('building_admin', 'parkingAllocations.read', true),
    ('building_admin', 'parkingAllocations.end', true),
    ('building_admin', 'vehicles.create', true),
    ('building_admin', 'vehicles.read', true),
    ('building_admin', 'vehicles.update', true),
    ('building_admin', 'vehicles.delete', true),
    ('building_admin', 'visitors.create', true),
    ('building_admin', 'visitors.read', true),
    ('building_admin', 'visitors.update', true),
    ('building_admin', 'broadcasts.read', true),
    ('building_admin', 'broadcasts.write', true),
    ('building_admin', 'notifications.read', true),
    ('building_admin', 'notifications.write', true),
    ('building_admin', 'messaging.read', true),
    ('building_admin', 'messaging.write', true),

    ('building_manager', 'buildings.read', true),
    ('building_manager', 'buildings.write', true),
    ('building_manager', 'units.read', true),
    ('building_manager', 'units.write', true),
    ('building_manager', 'building.assignments.read', true),
    ('building_manager', 'leases.read', true),
    ('building_manager', 'leases.documents.read', true),
    ('building_manager', 'leases.access_items.read', true),
    ('building_manager', 'leases.occupants.read', true),
    ('building_manager', 'leases.move_in', true),
    ('building_manager', 'leases.move_out', true),
    ('building_manager', 'contracts.read', true),
    ('building_manager', 'contracts.documents.read', true),
    ('building_manager', 'contracts.occupants.read', true),
    ('building_manager', 'contracts.move_requests.review', true),
    ('building_manager', 'contracts.move_in.execute', true),
    ('building_manager', 'contracts.move_out.execute', true),
    ('building_manager', 'residents.read', true),
    ('building_manager', 'residents.write', true),
    ('building_manager', 'residents.profile.read', true),
    ('building_manager', 'residents.profile.write', true),
    ('building_manager', 'requests.read', true),
    ('building_manager', 'requests.write', true),
    ('building_manager', 'requests.assign', true),
    ('building_manager', 'requests.update_status', true),
    ('building_manager', 'requests.comment', true),
    ('building_manager', 'requests.owner_approval_override', true),
    ('building_manager', 'parkingSlots.read', true),
    ('building_manager', 'parkingAllocations.read', true),
    ('building_manager', 'vehicles.read', true),
    ('building_manager', 'visitors.create', true),
    ('building_manager', 'visitors.read', true),
    ('building_manager', 'visitors.update', true),
    ('building_manager', 'broadcasts.read', true),
    ('building_manager', 'broadcasts.write', true),
    ('building_manager', 'notifications.read', true),
    ('building_manager', 'notifications.write', true),
    ('building_manager', 'messaging.read', true),
    ('building_manager', 'messaging.write', true),

    ('building_staff', 'buildings.read', true),
    ('building_staff', 'units.read', true),
    ('building_staff', 'leases.read', true),
    ('building_staff', 'leases.documents.read', true),
    ('building_staff', 'leases.access_items.read', true),
    ('building_staff', 'leases.occupants.read', true),
    ('building_staff', 'contracts.read', true),
    ('building_staff', 'contracts.documents.read', true),
    ('building_staff', 'contracts.occupants.read', true),
    ('building_staff', 'residents.read', true),
    ('building_staff', 'residents.profile.read', true),
    ('building_staff', 'requests.read', true),
    ('building_staff', 'requests.update_status', true),
    ('building_staff', 'requests.comment', true),
    ('building_staff', 'parkingSlots.read', true),
    ('building_staff', 'parkingAllocations.read', true),
    ('building_staff', 'vehicles.read', true),
    ('building_staff', 'visitors.create', true),
    ('building_staff', 'visitors.read', true),
    ('building_staff', 'visitors.update', true),
    ('building_staff', 'broadcasts.read', true),
    ('building_staff', 'notifications.read', true),
    ('building_staff', 'notifications.write', true),
    ('building_staff', 'messaging.read', true),
    ('building_staff', 'messaging.write', true),

    ('platform_superadmin', 'platform.org.create', false),
    ('platform_superadmin', 'platform.org.read', false),
    ('platform_superadmin', 'platform.org.admin.create', false),
    ('platform_superadmin', 'platform.org.admin.read', false),
    ('platform_superadmin', 'visitors.create', false),
    ('platform_superadmin', 'visitors.read', false),
    ('platform_superadmin', 'visitors.update', false)
)
INSERT INTO "RolePermission" ("roleId", "permissionId", "createdAt")
SELECT
  r."id",
  p."id",
  CURRENT_TIMESTAMP
FROM desired_role_permissions desired
INNER JOIN "Role" r
  ON r."key" = desired."roleKey"
 AND (
   (desired."orgScoped" = true AND r."orgId" IS NOT NULL)
   OR
   (desired."orgScoped" = false AND r."orgId" IS NULL)
 )
INNER JOIN "Permission" p
  ON p."key" = desired."permissionKey"
ON CONFLICT ("roleId", "permissionId") DO NOTHING;
